use axum::{
    body::Body,
    http::{header, StatusCode},
    response::{IntoResponse, Response},
};
use serde::{Deserialize, Serialize};
use utoipa::ToSchema;

/// Standard RFC 7807 Problem Details representation for HTTP APIs.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, ToSchema)]
pub struct ProblemDetails {
    /// A URI reference that identifies the problem type.
    #[serde(rename = "type")]
    pub r#type: String,

    /// A short, human-readable summary of the problem type.
    pub title: String,

    /// The HTTP status code generated by the origin server for this occurrence of the problem.
    pub status: u16,

    /// A human-readable explanation specific to this occurrence of the problem.
    pub detail: String,

    /// A URI reference that identifies the specific occurrence of the problem.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub instance: Option<String>,

    /// Optional list of invalid parameters for validation failures.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub invalid_params: Option<Vec<InvalidParam>>,
}

/// Description of an invalid request parameter for validation error details.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, ToSchema)]
pub struct InvalidParam {
    /// Name of the invalid field or parameter.
    pub name: String,

    /// Reason explaining why the field or parameter is invalid.
    pub reason: String,
}

impl ProblemDetails {
    /// Creates a new `ProblemDetails` with default type URI for standard status codes.
    #[must_use]
    pub fn new(status: StatusCode, title: impl Into<String>, detail: impl Into<String>) -> Self {
        let r#type = match status {
            StatusCode::BAD_REQUEST => "urn:problem-type:bad-request",
            StatusCode::UNAUTHORIZED => "urn:problem-type:unauthorized",
            StatusCode::FORBIDDEN => "urn:problem-type:forbidden",
            StatusCode::NOT_FOUND => "urn:problem-type:not-found",
            StatusCode::CONFLICT => "urn:problem-type:conflict",
            StatusCode::UNPROCESSABLE_ENTITY => "urn:problem-type:unprocessable-entity",
            StatusCode::INTERNAL_SERVER_ERROR => "urn:problem-type:internal-server-error",
            StatusCode::SERVICE_UNAVAILABLE => "urn:problem-type:service-unavailable",
            _ => "about:blank",
        }
        .to_string();

        Self {
            r#type,
            title: title.into(),
            status: status.as_u16(),
            detail: detail.into(),
            instance: None,
            invalid_params: None,
        }
    }

    /// Sets a custom `type` URI for this problem detail.
    #[must_use]
    pub fn with_type(mut self, r#type: impl Into<String>) -> Self {
        self.r#type = r#type.into();
        self
    }

    /// Sets an `instance` URI identifying the specific occurrence of this problem.
    #[must_use]
    pub fn with_instance(mut self, instance: impl Into<String>) -> Self {
        self.instance = Some(instance.into());
        self
    }

    /// Sets the `invalid_params` collection for validation errors.
    #[must_use]
    pub fn with_invalid_params(mut self, invalid_params: Vec<InvalidParam>) -> Self {
        self.invalid_params = Some(invalid_params);
        self
    }

    /// Convenience constructor for 400 Bad Request problem details.
    #[must_use]
    pub fn bad_request(detail: impl Into<String>) -> Self {
        Self::new(StatusCode::BAD_REQUEST, "Bad Request", detail)
    }

    /// Convenience constructor for 404 Not Found problem details.
    #[must_use]
    pub fn not_found(detail: impl Into<String>) -> Self {
        Self::new(StatusCode::NOT_FOUND, "Not Found", detail)
    }

    /// Convenience constructor for 409 Conflict problem details.
    #[must_use]
    pub fn conflict(detail: impl Into<String>) -> Self {
        Self::new(StatusCode::CONFLICT, "Conflict", detail)
    }

    /// Convenience constructor for 500 Internal Server Error problem details.
    /// Uses safe, generic message to prevent information leakage.
    #[must_use]
    pub fn internal_server_error() -> Self {
        Self::new(
            StatusCode::INTERNAL_SERVER_ERROR,
            "Internal Server Error",
            "An unexpected internal server error occurred. Please try again later.",
        )
    }

    /// Convenience constructor for 503 Service Unavailable problem details.
    #[must_use]
    pub fn service_unavailable(detail: impl Into<String>) -> Self {
        Self::new(
            StatusCode::SERVICE_UNAVAILABLE,
            "Service Unavailable",
            detail,
        )
    }
}

impl IntoResponse for ProblemDetails {
    fn into_response(self) -> Response {
        let status = StatusCode::from_u16(self.status).unwrap_or(StatusCode::INTERNAL_SERVER_ERROR);

        let json_body = match serde_json::to_string(&self) {
            Ok(body) => body,
            Err(_) => {
                return (
                    StatusCode::INTERNAL_SERVER_ERROR,
                    [(header::CONTENT_TYPE, "text/plain; charset=utf-8")],
                    "Failed to serialize problem details response",
                )
                    .into_response();
            }
        };

        Response::builder()
            .status(status)
            .header(header::CONTENT_TYPE, "application/problem+json")
            .body(Body::from(json_body))
            .unwrap_or_else(|_| {
                (
                    status,
                    [(header::CONTENT_TYPE, "application/problem+json")],
                    serde_json::to_string(&self).unwrap_or_default(),
                )
                    .into_response()
            })
    }
}

/// Unified application error enumeration implementing `thiserror::Error` and `IntoResponse`.
#[derive(thiserror::Error, Debug)]
pub enum AppError {
    #[error("Bad Request: {0}")]
    BadRequest(String),

    #[error("Validation Error: {0}")]
    ValidationError(String),

    #[error("Resource Not Found: {0}")]
    NotFound(String),

    #[error("Resource Conflict: {0}")]
    Conflict(String),

    #[error("Database Error: {0}")]
    Database(#[from] sqlx::Error),

    #[error("Internal Server Error: {0}")]
    Internal(String),

    #[error("Service Unavailable: {0}")]
    ServiceUnavailable(String),
}

impl IntoResponse for AppError {
    fn into_response(self) -> Response {
        let problem = match self {
            AppError::BadRequest(detail) => {
                tracing::warn!(detail = %detail, "Client sent bad request");
                ProblemDetails::bad_request(detail)
            }
            AppError::ValidationError(detail) => {
                tracing::warn!(detail = %detail, "Request validation failed");
                ProblemDetails::new(StatusCode::BAD_REQUEST, "Validation Error", detail)
                    .with_type("urn:problem-type:validation-error")
            }
            AppError::NotFound(detail) => {
                tracing::info!(detail = %detail, "Requested resource not found");
                ProblemDetails::not_found(detail)
            }
            AppError::Conflict(detail) => {
                tracing::warn!(detail = %detail, "Resource conflict occurred");
                ProblemDetails::conflict(detail)
            }
            AppError::Database(err) => {
                // Check if this is a unique constraint violation (PostgreSQL 23505)
                let is_unique_violation = if let sqlx::Error::Database(ref db_err) = err {
                    db_err.is_unique_violation()
                        || db_err.code().as_deref() == Some("23505")
                        || db_err.message().to_lowercase().contains("unique")
                        || db_err.message().to_lowercase().contains("duplicate")
                } else {
                    let err_str = err.to_string().to_lowercase();
                    err_str.contains("unique constraint") || err_str.contains("duplicate key")
                };

                if is_unique_violation {
                    tracing::warn!(error = %err, "Database unique constraint violation");
                    ProblemDetails::conflict(
                        "A record with the given identifier or data already exists.",
                    )
                } else {
                    // Security requirement: Log technical details on server, never leak to client!
                    tracing::error!(error = %err, "Internal database error occurred");
                    ProblemDetails::internal_server_error()
                }
            }
            AppError::Internal(internal_reason) => {
                // Security requirement: Log technical details on server, never leak to client!
                tracing::error!(error = %internal_reason, "Internal server error occurred");
                ProblemDetails::internal_server_error()
            }
            AppError::ServiceUnavailable(detail) => {
                tracing::error!(detail = %detail, "Service is currently unavailable");
                ProblemDetails::service_unavailable(detail)
            }
        };

        problem.into_response()
    }
}

/// Standard `Result` type alias for application handler return types.
pub type AppResult<T> = Result<T, AppError>;

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_problem_details_serialization_fields() {
        let problem = ProblemDetails::new(
            StatusCode::BAD_REQUEST,
            "Bad Request",
            "Field 'name' cannot be empty",
        )
        .with_instance("/users/validate");

        let json_str = serde_json::to_string(&problem).unwrap_or_default();
        let val: serde_json::Value = serde_json::from_str(&json_str).unwrap_or_default();

        assert_eq!(val["type"], "urn:problem-type:bad-request");
        assert_eq!(val["title"], "Bad Request");
        assert_eq!(val["status"], 400);
        assert_eq!(val["detail"], "Field 'name' cannot be empty");
        assert_eq!(val["instance"], "/users/validate");
    }

    #[test]
    fn test_problem_details_with_invalid_params() {
        let problem = ProblemDetails::bad_request("Validation failed").with_invalid_params(vec![
            InvalidParam {
                name: "email".to_string(),
                reason: "Must be a valid email address".to_string(),
            },
            InvalidParam {
                name: "name".to_string(),
                reason: "Cannot be blank".to_string(),
            },
        ]);

        let json_str = serde_json::to_string(&problem).unwrap_or_default();
        let val: serde_json::Value = serde_json::from_str(&json_str).unwrap_or_default();

        assert_eq!(val["status"], 400);
        assert_eq!(val["invalid_params"].as_array().map(|a| a.len()), Some(2));
        assert_eq!(val["invalid_params"][0]["name"], "email");
        assert_eq!(val["invalid_params"][1]["name"], "name");
    }

    #[test]
    fn test_internal_server_error_hides_sensitive_details() {
        let sensitive_sql_error = AppError::Internal(
            "FATAL: password authentication failed for user 'postgres' at 10.0.0.1:5432"
                .to_string(),
        );

        let response = sensitive_sql_error.into_response();
        assert_eq!(response.status(), StatusCode::INTERNAL_SERVER_ERROR);

        let problem = ProblemDetails::internal_server_error();
        let json_str = serde_json::to_string(&problem).unwrap_or_default();

        // Verify no leak of credentials, IP, SQL, or internal details
        assert!(!json_str.contains("FATAL"));
        assert!(!json_str.contains("password"));
        assert!(!json_str.contains("10.0.0.1"));
        assert!(!json_str.contains("postgres"));
        assert_eq!(problem.status, 500);
        assert_eq!(problem.title, "Internal Server Error");
    }

    #[test]
    fn test_app_error_bad_request_into_response() {
        let err = AppError::BadRequest("Invalid query parameter".to_string());
        let res = err.into_response();
        assert_eq!(res.status(), StatusCode::BAD_REQUEST);
        assert_eq!(
            res.headers()
                .get(header::CONTENT_TYPE)
                .and_then(|v| v.to_str().ok()),
            Some("application/problem+json")
        );
    }

    #[test]
    fn test_app_error_not_found_into_response() {
        let err = AppError::NotFound("User 123 not found".to_string());
        let res = err.into_response();
        assert_eq!(res.status(), StatusCode::NOT_FOUND);
    }

    #[test]
    fn test_app_error_conflict_into_response() {
        let err = AppError::Conflict("Email already exists".to_string());
        let res = err.into_response();
        assert_eq!(res.status(), StatusCode::CONFLICT);
    }

    #[test]
    fn test_app_error_service_unavailable_into_response() {
        let err = AppError::ServiceUnavailable("Database down".to_string());
        let res = err.into_response();
        assert_eq!(res.status(), StatusCode::SERVICE_UNAVAILABLE);
    }
}
